export const PERFORMANCE_TYPE_DEFAULT = 'DEFAULT'
export const PERFORMANCE_TYPE_BAR = 'BAR'
export const PERFORMANCE_TYPE_ARM = 'ARM'

export const PERFORMANCE_TYPES = [
  PERFORMANCE_TYPE_DEFAULT,
  PERFORMANCE_TYPE_BAR,
  PERFORMANCE_TYPE_ARM,
]
